// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrqOWf3i70FOf4d42w3LUrKKj_3FkzrMw',
    appId: '1:122941288895:android:93e61a28d057c386c5310a',
    messagingSenderId: '122941288895',
    projectId: 'final-exam-c7343',
    storageBucket: 'final-exam-c7343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6zSG_jIFd57e0Vdr3gscaS0jUkq_62JA',
    appId: '1:122941288895:ios:d5c418f30bb31378c5310a',
    messagingSenderId: '122941288895',
    projectId: 'final-exam-c7343',
    storageBucket: 'final-exam-c7343.firebasestorage.app',
    iosBundleId: 'com.example.firebaseExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQKjQBDhAqDwK0l-CQQ1hGrrgttpIEBBE',
    appId: '1:122941288895:web:2faf765880605045c5310a',
    messagingSenderId: '122941288895',
    projectId: 'final-exam-c7343',
    authDomain: 'final-exam-c7343.firebaseapp.com',
    storageBucket: 'final-exam-c7343.firebasestorage.app',
  );
}
